name: Test SSH Connection to Azure VM

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository (optional, you can remove this if you don't need the repo code for this test)
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: SSH to the Azure VM and run a simple command (e.g., 'uptime' to check VM status)
    - name: Test SSH Connection to Azure VM
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        port: 22
        script: |
          echo "Connected successfully!"
          uptime  # Run a basic command to check if the VM is running correctly
